trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - name: SolutionName
    value: TODO #TODO: Replace with your solution name
  - name: EnvironmentName
    value: TODO #TODO: Replace with your Azure DevOps environment name
  - name: PowerPlaformServiceConnection
    value: TODO #TODO: Replace with your service connection name
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build Web Resources
    jobs:
      - job: build
        steps:
          - task: UseNode@1
            displayName: Install Node.js 24
            inputs:
              version: '24.x'
          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(pnpm_config_cache)
            displayName: Cache pnpm
          - script: |
              npm install --global corepack@latest
              corepack enable
              corepack prepare pnpm@latest-11 --activate
              pnpm config set store-dir $(pnpm_config_cache)
            displayName: Setup pnpm
          - script: pnpm install
            displayName: Install npm packages
          - script: pnpm run build:prod
            displayName: Run build script
          - task: CopyFiles@2
            displayName: Copy Web Resources to Staging Directory
            inputs:
              Contents: |
                dist/**
                .config/dotnet-tools.json
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishPipelineArtifact@1
            displayName: Publish Web Resources as Pipeline Artifacts
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'webresources'
              publishLocation: 'pipeline'
  - stage: push
    displayName: Push Web Resources
    condition: and(succeeded(), eq(variables['build.sourceBranch'],'refs/heads/main'))
    jobs:
      - deployment: push
        environment: $(EnvironmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  displayName: Use .NET 10
                  inputs:
                    packageType: 'sdk'
                    version: '10.x'
                - script: dotnet tool restore
                  workingDirectory: $(Pipeline.Workspace)/webresources
                  displayName: Install dgtp
                - task: PowerPlatformSetConnectionVariables@2
                  displayName: 'Power Platform Set Connection Variables'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: $(PowerPlaformServiceConnection)
                - script: |
                    dotnet tool run dgtp push ./dist --solution $(SolutionName) --publish
                  workingDirectory: $(Pipeline.Workspace)/webresources
                  displayName: Register Web Resources
                  env:
                    "dgtp:xrm:connection": $(PowerPlatformSetConnectionVariables.BuildTools.DataverseConnectionString)
